site_name: Allocation Optimization Tooling

theme:
    name: 'material'
    Logo: images/logo.png
    features:
     - navigation.top
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 

nav:
   - Index: index.md
   - Overview:
     - General: General.md
     - Quickstart: Quickstart.md
     - Transparency, Caution and Risk: caution.md
     - Usage and Parameters: usage.md
     - Changelog : Changelog.md
     - Roadmap: Roadmap.mg
   - Technology:
     - Architecture: Architecture.md
     - Indexing Rewards: indexing_rewards.md
     - Developer: Developer.md